type VercelRequest = import('@vercel/node').VercelRequest;
type VercelResponse = import('@vercel/node').VercelResponse;
type RequestHandler = import('express').RequestHandler;

function loadApp(): RequestHandler {
  const candidates = [
    "../dist/backend-lib/app.js",           // preferred: generated by npm run build
    "../backend-cjs/backend-lib/app.js",    // fallback: copy of compiled backend
    "../backend-cjs/app.js",                // legacy fallback
  ];

  for (const modPath of candidates) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const mod = require(modPath);
      console.log("[api] using backend module", modPath);
      return (mod.default ?? mod) as RequestHandler;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn("[api] backend module not found at", modPath, msg);
    }
  }

  throw new Error("backend module missing; ensure dist/backend-lib/app.js is built and included");
}

const app = loadApp();

const handler = (req: VercelRequest, res: VercelResponse) => {
  console.log("[API HIT]", req.method, req.url);
  return app(req as any, res as any, () => {});
};

module.exports = handler;
